### PR TITLE
Add status 500 to error response

### PR DESCRIPTION
**Pull request by skirsten**
so that debugging in the dev-tools is easier :)

### CODE REVIEW

**Comment by skirsten** [comment]
Hmm, maybe this was intentionally: https://github.com/Janpot/next-rpc/blob/a9a8027d081db32190abc5b16e618e2612baa45a/test/rpc.spec.ts#L63

**Comment by Janpot** [comment]
The client needs to be able to distinguish between expected errors and unexpected errors. You're conflating transport level errors with rpc level errors and the tests cover this situation. See the previous attempt here with a counterexample on why you don't want to mess with the statuscode here: https://github.com/Janpot/next-rpc/pull/28

**Comment by skirsten** [comment]
Okay, yes, that makes sense. I should have searched first.

**Comment by Janpot** [comment]
I'm reopening https://github.com/Janpot/next-rpc/issues/19#issuecomment-1086703405

**Pull request closed without merging**
