### PR TITLE
Fix #40

### LINKED ISSUE #40: Cannot use context and _middleware in Next `12.1.6`
Enabling context on latest next with a _middleware file will throw on build
```
Module not found: Can't resolve 'async_hooks' in '/vercel/path0/node_modules/.pnpm/next-rpc@3.4.3_next@12.1.6/node_modules/next-rpc/dist'
```

This is because the _middleware file is treated as a page in babel plugin and latest next throws if the _middleware file imports stuff from node built ins

### PR DESCRIPTION
**Pull request by remorses**
Fix #40

Don't apply the `next-rpc` babel plugin to _middleware files

### CODE REVIEW

**Comment by remorses** [comment]
I personally don't see how this would be useful, getContext makes sense inside rpc functions to get req and res, in middleware you already have req and res

**Comment by remorses** [comment]
Hey, is there anything blocking this?

**Comment by Janpot** [comment]
cuurently `getContext` is not rpc-only. It works regardless of whether you use rpc or not because it operates on 
- api routes
- getServerSideProps
- getInitialProps

Any code called by any of these entry points can use `getContext`.  rpc is built on top of API routes, so it can use context. 
`_middleware` is a new entrypoint, so the question becomes: what should happen when a function that is called by `_middleware` uses `getContext`.

**Comment by remorses** [comment]
Given that the current behavior is broken right now can you merge this and think of a better solution later? I really want to update my app to latest next to get some fixes

**Comment by Janpot** [comment]
I'll merge it if you make `getContext` throw an error `Context is currently not supported for Next.js middleware` when called downstream from middleware.

**Comment by Janpot** [comment]
Thanks. I published this as v3.5.1

**Comment by remorses** [comment]
Thank you 🙏

**Pull request merged**
